package assets

object PageTitles {
  val checkAnswersGroupStructure = "Check parent company details"
  val enterANGIE = "Enter the adjusted net group-interest expense (ANGIE)"
  val groupRatioElection = "Are you making a group ratio election?"
  val checkAnswersReportingCompany = "Check your answers - About the reporting company"
  val reportingCompanyCRN = "Company Registration Number (CRN)"
  val reportingCompanyCTUTR = "UK Tax reference"
  val reportingCompanyName = "Reporting company name"
  val groupInterestAllowance = "What is the group interest allowance for the period?"
  val groupInterestCapacity = "What is the group interest capacity for the period?"
  val groupSubjectToReactivations = "Is the group subject to reactivations?"
  val groupSubjectToRestrictions = "Is the group subject to restrictions?"
  val infrastructureCompanyElection = "Has the group made the Infrastructure company election?"
  val interestAllowanceBroughtForward = "What is the group interest allowance brought forward?"
  val interestReactivationsCap = "What is the group reactivation cap?"
  val returnContainEstimates = "Does the return contain estimates?"
  val revisingReturn = "Are you revising a return you have already submitted?"
  val agentActingOnBehalfOfCompany = "Are you an agent acting on behalf of a company?"
  val agentName = "Agent name"
  val fullOrAbbreviatedReturn = "Do you want to submit a full or abbreviated return?"
  val reportingCompanyAppointed = "Has the reporting company been appointed"
  val reportingCompanyRequired = "A reporting company is required"
  val confirmation = "Return submitted"
  val continueSavedReturn = "Do you want to start a new return or continue working on a saved return?"
  val deemedParent = "Does the group have a ’deemed’ parent company?"
  val parentCompanyName = "Enter the name of the parent company"
  val parentCRN = "Parent Company Registration Number"
  val payTaxInUk: String => String = name => s"Does $name have a Unique Taxpayer Reference?"
  val reportingCompanySameAsParent: String => String = name => s"Is $name also the parent company?"
  val parentCompanySAUTR = "Parent company Self Assessment Unique Taxpayer Reference"
  val parentCompanyCTUTR = "Parent Company Corporation Unique Taxpayer Reference"
  val registeredCompaniesHouse = "Is the parent company registered with companies house?"
  val savedReturn = "Your return has been saved"
  val registeredForTaxInAnotherCountry: String => String = name => s"Is $name registered for tax in another country?"
  val limitedLiabilityPartnership: String => String = name => s"Is $name a Limited Liability Partnership?"
  val localRegistrationNumber: String => String = name => s"Enter $name’${if(name.last.toLower != 's')'s'} local Registration Number"
  val countryOfIncorporation: String => String = name => s"Where is $name registered for tax?"

}
